services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file: ./auth-service/.env
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_auth
    depends_on:
      - mongodb

  register-service:
    build: ./register-service
    ports:
      - "3002:3002"
    env_file: ./register-service/.env
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_register
    depends_on:
      - mongodb

  target-service:
    build: ./target-service
    ports:
      - "3003:3003"
    env_file: ./target-service/.env
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_target
    volumes:
      - ./target-service/src/uploads:/usr/src/app/src/uploads
    depends_on:
      - mongodb

  score-service:
    build: ./score-service
    ports:
      - "3004:3004"
    env_file: ./score-service/.env
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_score
    depends_on:
      - mongodb

  clock-service:
    build: ./clock-service
    ports:
      - "3005:3005"
    env_file: ./clock-service/.env
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_clock
    depends_on:
      - mongodb

  mail-service:
    build: ./mail-service
    ports:
      - "3006:3006"
    env_file: ./mail-service/.env
    environment:
      - PORT=3006
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_mail
    depends_on:
      - mongodb

  read-service:
    build: ./read-service
    ports:
      - "3007:3007"
    env_file: ./read-service/.env
    environment:
      - PORT=3007
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_read
    depends_on:
      - mongodb

volumes:
  mongo-data:
