services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  auth-service:
    build: ./auth-service
    env_file: ./auth-service/.env
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_auth
    depends_on:
      - mongodb

  register-service:
    build: ./register-service
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_register
      - TARGET_SERVICE_URL=http://target-service:3003
    depends_on:
      - mongodb
      - target-service

  target-service:
    build: ./target-service
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_target
      - SCORE_SERVICE_URL=http://score-service:3004
      - BASE_URL=http://localhost:3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./target-service/src/uploads:/usr/src/app/src/uploads
    depends_on:
      - mongodb
      - rabbitmq

  score-service:
    build: ./score-service
    env_file: ./score-service/.env
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_score
      - TARGET_SERVICE_URL=http://target-service:3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - target-service
      - mongodb
      - rabbitmq

  clock-service:
    build: ./clock-service
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_clock
      - TARGET_SERVICE_URL=http://target-service:3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  mail-service:
    build: ./mail-service
    env_file: ./mail-service/.env
    environment:
      - PORT=3006
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_mail
      - REGISTER_SERVICE_URL=http://register-service:3002
      - AUTH_SERVICE_URL=http://auth-service:3001
      - TARGET_SERVICE_URL=http://target-service:3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  read-service:
    build: ./read-service
    environment:
      - PORT=3007
      - MONGO_URI=mongodb://mongodb:27017/photo_prestiges_read
      - REGISTER_SERVICE_URL=http://register-service:3002
      - SCORE_SERVICE_URL=http://score-service:3004
    depends_on:
      - mongodb

  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=super_secret_key
      - AUTH_SERVICE_URL=http://auth-service:3001
      - REGISTER_SERVICE_URL=http://register-service:3002
      - TARGET_SERVICE_URL=http://target-service:3003
      - SCORE_SERVICE_URL=http://score-service:3004
      - CLOCK_SERVICE_URL=http://clock-service:3005
      - MAIL_SERVICE_URL=http://mail-service:3006
      - READ_SERVICE_URL=http://read-service:3007
    depends_on:
      - auth-service
      - register-service
      - target-service
      - score-service
      - clock-service
      - mail-service
      - read-service

volumes:
  mongo-data:
  rabbitmq-data:
